# Generated by Django 5.0.1 on 2024-04-18 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("RecipeFinder", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hasingredient",
            name="quantity",
            field=models.FloatField(),
        ),
    ]
