# Generated by Django 5.0.4 on 2024-05-14 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("RecipeFinder", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="ingredient",
            old_name="ingredient",
            new_name="name",
        ),
    ]
