# Generated by Django 5.0.1 on 2024-04-17 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("RecipeFinder", "0002_hasstep_index_alter_user_isadmin"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="imageURL",
            field=models.URLField(null=True),
        ),
    ]
