# Generated by Django 5.0.1 on 2024-04-18 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("RecipeFinder", "0002_alter_hasingredient_quantity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="image",
            field=models.ImageField(null=True, upload_to="images/"),
        ),
    ]
