# Generated by Django 5.0.1 on 2024-04-18 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("RecipeFinder", "0003_recipe_imageurl"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="HasStep",
            new_name="Step",
        ),
    ]
