# Generated by Django 5.0.4 on 2024-05-14 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("RecipeFinder", "0003_alter_recipe_course"),
    ]

    operations = [
        migrations.RenameField(
            model_name="recipe",
            old_name="author",
            new_name="chef",
        ),
    ]
